# .config/alacritty/alacritty.toml
[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.9
padding.x = 0
padding.y = 0

[window.dimensions]
columns = 260
lines = 120

[cursor.style]
shape= "Beam"
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "MesloLGS Nerd Font Mono"
normal.style = "Bold"
size = 11.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"
